insert into employees (employee_id,
                       first_name,
                       last_name,
                       email,
                       phone_number,
                       hire_date,
                       job_id,
                       salary,
                       commission_pct,
                       manager_id,
                       department_id,
                       cpf)
                       values (-1, 'Ricardo', 'Chagas', 'rchagas@spread.com,br', '11111111', sysdate - 1000, 'DIG_LEADER', 11111, null, null, 11,  '53130220755');
                       
